apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydeployment
spec:
  replicas: 3
  selector:
    matchlabels:
     env: dev
  template:
    metadata:
        labels:
           env: dev
    spec:
      containers:
        - name: nginxccontainer
          image: nginx
          ports:
            - containerPort: 80
